baseURL = "https://juancer.me/"
languageCode = "en-us"
title = "juancer.me"
copyright = "© Juan Cerdeño 2024"
theme = "simple"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "pastie"

[build]
  [build.buildStats]
    enable = true


