baseURL = "https://juancer.me/"
languageCode = "en-us"
title = "Juan Cerdeño"
copyright = "(c) Juan Cerdeño 2025"
theme = "simple"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "pastie"

[build]
  [build.buildStats]
    enable = true


