baseURL = "https://ajuancer.github.io/"
languageCode = "en-us"
title = "ajuancer.github.io"
copyright = "© Juan Cerdeño 2021"
theme = "Simple"
[params]
  copyrightTemplate = "© Juan Cerdeño {year}"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "pastie"
#     noClases = false
#
# pygmentsUseClasses = true
# pygmentsCodeFences = true